### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by gregbo**

### CODE REVIEW

**Comment by gregbo** [comment]
reword Diffie-Hellman section in ssh.rst
correct grammar in tcp.rst

**Review by obonaventure — CHANGES_REQUESTED** [review]
Thanks for the suggestion. I'm a bit concerned by the definition of the generator and the subgroup which will probably not be understood by most students. rfc4253 is a good reference for ssh, but not for the mathematics behind DH. Do you know other accessible references that define generator, subgroup and Galois field in an accessible manner ?

**Comment by gregbo** [comment]
The [Diffie-Hellman Protocol](https://mathworld.wolfram.com/Diffie-HellmanProtocol.html) page in Wolfram MathWorld references Schneier's **_[Applied Cryptography](https://www.schneier.com/books/applied-cryptography/)_**, which is highly regarded as a reference for the math and CS principles that cryptography is based on.  There are many other Wolfram MathWorld pages that cover the details of generator, subgroup, and Galois field.

**Review by obonaventure — APPROVED** [review]
Please add your name to the AUTHORS file and in the preface. In the preface, please also add it to the spelling directive so that the spell checker does not complain. Thanks for your contribution

**Comment by gregbo** [comment]
- add citations, spelling, etc. for Schneier text
- add Greg Skinner to AUTHORS, etc.
- make minor edits to tcp.rst

**Pull request merged**
